apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nubi
spec:
  selector:
    matchLabels:
      run: demo-nubi
  replicas: 2
  template:
    metadata:
      labels:
        run: demo-nubi
    spec:
      containers:
      - name: demo-nubi
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
         name: nginx-conf
         subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-index-html-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
data: |
  <html>
<head>
<title>Welcome to Nubi!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nubi
  labels:
    run: demo-nubi
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    run: demo-nubi
